// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqnodxqhenptxdmclutq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxbm9keHFoZW5wdHhkbWNsdXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTA1NjYsImV4cCI6MjA1OTc2NjU2Nn0.Go6QaWmFq76XBqpQaZ-G23oHxhtbnvwfetP427eeiHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);